
CREATE GENERATOR GEN_ACTIVITIES_ID;
CREATE GENERATOR GEN_DISTRICTS_ID;
CREATE GENERATOR GEN_JOBS_ID;
CREATE GENERATOR GEN_MANAGERS_ID;
CREATE GENERATOR GEN_QUESTIONNAIRES_ID;
CREATE GENERATOR GEN_SMR_ADD_EDUCATIONS_ID;
CREATE GENERATOR GEN_SUMMARIES_ID;
CREATE GENERATOR GEN_SUMMARY_EDUCATIONS_ID;
CREATE GENERATOR GEN_SUMMARY_RECOMENDATIONS_ID;
CREATE GENERATOR GEN_SUMMARY_WORK_ACTIVITIES_ID;
CREATE GENERATOR GEN_VACANSIES_ID;


SET TERM ^ ; 



/******************************************************************************/
/****                          Stored Procedures                           ****/
/******************************************************************************/

CREATE PROCEDURE SET_USER_TUNING (
    ITEM_NAME VARCHAR(100),
    TUNING BLOB SUB_TYPE 0 SEGMENT SIZE 80)
AS
BEGIN
  EXIT;
END^



SET TERM ; ^


/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/

CREATE TABLE ACTIVITIES (
    ID           INTEGER NOT NULL,
    NAME         VARCHAR(100),
    CREATOR      VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER      VARCHAR(31),
    CHANGE_DATE  TIMESTAMP
);

CREATE TABLE DISTRICTS (
    ID           INTEGER NOT NULL,
    NAME         VARCHAR(50),
    CREATOR      VARCHAR(31) DEFAULT current_user NOT NULL,
    CREATE_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER      VARCHAR(31),
    CHANGE_DATE  TIMESTAMP
);

CREATE TABLE JOBS (
    ID           INTEGER NOT NULL,
    ACTIVITY_ID  INTEGER NOT NULL,
    NAME         VARCHAR(100),
    CREATOR      VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER      VARCHAR(31),
    CHANGE_DATE  TIMESTAMP
);

CREATE TABLE MANAGERS (
    ID           INTEGER NOT NULL,
    NAME         VARCHAR(150) NOT NULL,
    VALID        INTEGER default 1 NOT NULL,
    PSWD         VARCHAR(8) DEFAULT '' NOT NULL,
    CREATOR      VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER      VARCHAR(31),
    CHANGE_DATE  TIMESTAMP
);

CREATE TABLE QUESTIONNAIRES (
    ID                               INTEGER NOT NULL,
    MANAGER_ID                       INTEGER NOT NULL,
    MANAGER_NOTES                    VARCHAR(500),
    NUMBER_DOC                       INTEGER NOT NULL,
    STATUS_DOC                       INTEGER NOT NULL,
    LAST_CHANGE_STATUS_DATE          DATE,
    FIO                              VARCHAR(150) NOT NULL,
    ADDRESS                          VARCHAR(300) NOT NULL,
    PHONE                            VARCHAR(50) NOT NULL,
    E_MAIL                           VARCHAR(50),
    YOUR_SEX                         INTEGER NOT NULL,
    YOUR_BIRTHDAY                    DATE NOT NULL,
    YOUR_HEIGH                       VARCHAR(50),
    YOUR_WEIGHT                      VARCHAR(50),
    YOUR_EYES_COLOR                  VARCHAR(50),
    YOUR_HAIR_COLOR                  VARCHAR(50),
    YOUR_NATIONALITY                 VARCHAR(50),
    YOUR_MARRIAGE_STATUS             VARCHAR(50) NOT NULL,
    YOUR_CHILDREN_INFORMATION        VARCHAR(100) NOT NULL,
    YOUR_WISH_BABY_BIRTH             INTEGER NOT NULL,
    YOUR_EDUCATION_LEVEL             INTEGER NOT NULL,
    YOUR_ACTIVITY                    VARCHAR(100) NOT NULL,
    YOUR_LIVING_SPACE_CONDITION      VARCHAR(100) NOT NULL,
    YOUR_OVER_PRIVACY                VARCHAR(100) NOT NULL,
    YOUR_HOBBY                       VARCHAR(100) NOT NULL,
    YOUR_SMOKING_ATTITUDE            VARCHAR(100) NOT NULL,
    YOUR_ALCOHOL_ATTITUDE            VARCHAR(100) NOT NULL,
    POSITIVE_TRAIT                   VARCHAR(100) NOT NULL,
    NEGATIVE_TRAIT                   VARCHAR(100) NOT NULL,
    OPPOSITE_PRIZE                   VARCHAR(100) NOT NULL,
    MAIN_IN_HOMELIFE                 VARCHAR(100) NOT NULL,
    YOUR_ADDITIONAL_INFORMATION      VARCHAR(100),
    ACQUAINTANCE_AIM                 INTEGER NOT NULL,
    OPPONENT_SEX                     INTEGER NOT NULL,
    OPPONENT_START_AGE               INTEGER NOT NULL,
    OPPONENT_STOP_AGE                INTEGER NOT NULL,
    OPPONENT_START_HEIGH             INTEGER,
    OPPONENT_STOP_HEIGH              INTEGER,
    OPPONENT_START_WEIGHT            INTEGER,
    OPPONENT_STOP_WEIGHT             INTEGER,
    OPPONENT_EYES_COLOR              VARCHAR(50),
    OPPONENT_HAIR_COLOR              VARCHAR(50),
    OPPONENT_NATIONALITY             VARCHAR(50),
    OPPONENT_MARRIAGE_STATUS         VARCHAR(50) NOT NULL,
    OPPONENT_CHILDREN_INFORMATION    VARCHAR(100) NOT NULL,
    OPPONENT_WISH_BABY_BIRTH         INTEGER NOT NULL,
    OPPONENT_EDUCATION_LEVEL         INTEGER NOT NULL,
    OPPONENT_ACTIVITY                VARCHAR(100) NOT NULL,
    OPPONENT_LIVING_SPACE_CONDITION  VARCHAR(100) NOT NULL,
    OPPONENT_OVER_PRIVACY            VARCHAR(100) NOT NULL,
    OPPONENT_HOBBY                   VARCHAR(100) NOT NULL,
    OPPONENT_SMOKING_ATTITUDE        VARCHAR(100) NOT NULL,
    OPPONENT_ALCOHOL_ATTITUDE        VARCHAR(100) NOT NULL,
    OPPONENT_ADDITIONAL_INFORMATION  VARCHAR(100),
    CREATOR                          VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER                          VARCHAR(31),
    CHANGE_DATE                      TIMESTAMP
);

CREATE TABLE SUMMARIES (
    ID                         INTEGER NOT NULL,
    MANAGER_ID                 INTEGER NOT NULL,
    MANAGER_NOTES              VARCHAR(500),
    NUMBER_DOC                 INTEGER NOT NULL,
    STATUS_DOC                 INTEGER NOT NULL,
    LAST_CHANGE_STATUS_DATE    DATE,
    FIO                        VARCHAR(150) NOT NULL,
    BIRTHDAY                   DATE NOT NULL,
    SEX                        INTEGER NOT NULL,
    CONTACT_PHONE              VARCHAR(50) NOT NULL,
    SERVICE_PHONE              VARCHAR(50),
    MOBILE_PHONE               VARCHAR(50),
    REGISTRATION_ADDRESS       VARCHAR(300) NOT NULL,
    RESIDING_ADDRESS           VARCHAR(300),
    RESIDING_DISTRICT_ID       INTEGER NOT NULL,
    PASSPORT_DATA              VARCHAR(300),
    E_MAIL                     VARCHAR(50),
    ACTIVITY_ID                INTEGER NOT NULL,
    JOB_ID                     INTEGER NOT NULL,
    MINIMAL_SUPPOSED_INCOME    VARCHAR(50) NOT NULL,
    WORK_SCHEDULE              INTEGER NOT NULL,
    OTHER_POSSIBLE_JOBS        VARCHAR(100),
    EDUCATION_LEVEL            INTEGER NOT NULL,
    WORK_EXPERIENCE            INTEGER,
    COMPUTER_EXPERIENCE        VARCHAR(200) NOT NULL,
    FOREIGN_LANGUAGE           VARCHAR(100),
    PROFESSIONAL_SKILL         VARCHAR(300),
    PROFESSIONAL_ACHIEVEMENTS  VARCHAR(500),
    FAMILY_STATUS              VARCHAR(100) NOT NULL,
    HAVE_DRIVING_LICENCE       INTEGER,
    HAVE_CAR                   INTEGER,
    PERSONAL_QUALITIES         VARCHAR(100),
    HOBBIES                    VARCHAR(100),
    OTHER_INFORMATION          VARCHAR(500),
    FOTO                       BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    DONT_PUBLISH               INTEGER,
    PUBLISH_IN_LIST            INTEGER,
    CREATOR                    VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE                TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER                    VARCHAR(31),
    CHANGE_DATE                TIMESTAMP
);

CREATE TABLE SUMMARY_ADDITIONAL_EDUCATIONS (
    ID                            INTEGER NOT NULL,
    SUMMARY_ID                    INTEGER NOT NULL,
    GRADUATION_YEAR               VARCHAR(50),
    EDUCATIONAL_INSTITUTION_NAME  VARCHAR(300),
    COURSE_NAME                   VARCHAR(200),
    CREATOR                       VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER                       VARCHAR(31),
    CHANGE_DATE                   TIMESTAMP
);

CREATE TABLE SUMMARY_EDUCATIONS (
    ID                            INTEGER NOT NULL,
    SUMMARY_ID                    INTEGER NOT NULL,
    ENTRANCE_YEAR                 VARCHAR(50),
    GRADUATION_YEAR               VARCHAR(50),
    EDUCATIONAL_INSTITUTION_NAME  VARCHAR(300),
    FACULTY_NAME                  VARCHAR(200),
    QUALIFICATION                 VARCHAR(100),
    CREATOR                       VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER                       VARCHAR(31),
    CHANGE_DATE                   TIMESTAMP
);

CREATE TABLE SUMMARY_RECOMENDATIONS (
    ID                 INTEGER NOT NULL,
    SUMMARY_ID         INTEGER NOT NULL,
    FIO                VARCHAR(150),
    ORGANIZATION_NAME  VARCHAR(300),
    JOB                VARCHAR(100),
    CONTACT_PHONE      VARCHAR(50),
    CREATOR            VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER            VARCHAR(31),
    CHANGE_DATE        TIMESTAMP
);

CREATE TABLE SUMMARY_WORK_ACTIVITIES (
    ID                 INTEGER NOT NULL,
    SUMMARY_ID         INTEGER NOT NULL,
    ENTRANCE_DATE      VARCHAR(50),
    RETIRING_DATE      VARCHAR(50),
    ORGANIZATION_NAME  VARCHAR(300) NOT NULL,
    ACTIVITY_ID        INTEGER,
    JOB                VARCHAR(100),
    FUNCTIONAL_DUTIES  VARCHAR(1024),
    CREATOR            VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER            VARCHAR(31),
    CHANGE_DATE        TIMESTAMP
);

CREATE TABLE USERS_TUNINGS (
    USER_NAME  VARCHAR(31) DEFAULT current_user NOT NULL,
    ITEM_NAME  VARCHAR(100) NOT NULL,
    TUNING     BLOB SUB_TYPE 0 SEGMENT SIZE 80 NOT NULL
);

CREATE TABLE VACANSIES (
    ID                       INTEGER NOT NULL,
    MANAGER_ID               INTEGER NOT NULL,
    MANAGER_NOTES            VARCHAR(500),
    NUMBER_DOC               INTEGER NOT NULL,
    STATUS_DOC               INTEGER NOT NULL,
    LAST_CHANGE_STATUS_DATE  DATE DEFAULT current_date,
    ORGANIZATION_NAME        VARCHAR(300) NOT NULL,
    BOSS                     VARCHAR(150),
    ACTIVITY_ID              INTEGER,
    RESPONSIBLE_PERSON       VARCHAR(150) NOT NULL,
    CPHONE                   VARCHAR(50) NOT NULL,
    E_MAIL                   VARCHAR(50),
    FOR_INET_ONLY            INTEGER DEFAULT 0 NOT NULL,
    JOB_ID                   INTEGER NOT NULL,
    JOB_DUTIES               VARCHAR(200) NOT NULL,
    IMMEDIATE_BOSS           VARCHAR(200) NOT NULL,
    PERSONS_UNDER            VARCHAR(50) NOT NULL,
    TRIAL_PERIOD             VARCHAR(50) NOT NULL,
    WORK_SCHEDULE            INTEGER,
    WORK_DAY                 VARCHAR(50) NOT NULL,
    WORK_WEEK                VARCHAR(50) NOT NULL,
    TRIAL_PAYMENT            VARCHAR(50) NOT NULL,
    PAYMENT                  VARCHAR(50) NOT NULL,
    PROSPECT_PAYMENT         VARCHAR(50),
    EMPLOYEE_STUDIES         VARCHAR(200),
    SALARY_PAYED             VARCHAR(50),
    OVERTIME_WORK_PAYED      VARCHAR(50),
    PRIVILEGE                VARCHAR(100),
    RISE_PROSPECT            VARCHAR(100),
    SELECTION_PERSON         VARCHAR(150),
    EDUCATION_LEVEL          INTEGER NOT NULL,
    EDUCATION                VARCHAR(200),
    COMPUTER_EXPERIENCE      VARCHAR(200) NOT NULL,
    FOREIGN_LANGUAGE         VARCHAR(100),
    SPESIAL_SKILLS           VARCHAR(200),
    WORK_EXPERIENCE          INTEGER,
    SEX                      INTEGER,
    MIN_AGE                  INTEGER,
    MAX_AGE                  INTEGER,
    APPEARANCE               VARCHAR(200),
    MARRIAGE_STATUS          INTEGER DEFAULT 0 NOT NULL,
    CHILDREN_INFORMATION     VARCHAR(100),
    FAMILY_STATUS            VARCHAR(100) DEFAULT '' NOT NULL,
    ARMY_DUTY                VARCHAR(200),
    REGISTRATION             VARCHAR(200),
    DISTRICT_ID              INTEGER,
    HAVE_HOME_PHONE          INTEGER,
    HAVE_DRIVING_LICENCE     INTEGER,
    HAVE_CAR                 INTEGER,
    ADDITIONAL_INFORMATION   VARCHAR(500),
    CREATOR                  VARCHAR(31) DEFAULT CURRENT_USER NOT NULL,
    CREATE_DATE              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHANGER                  VARCHAR(31),
    CHANGE_DATE              TIMESTAMP
);





/******************************************************************************/
/****                                Views                                 ****/
/******************************************************************************/


/* View: USER_LIST */
CREATE VIEW USER_LIST(
    USER_NAME)
AS
select M.NAME from MANAGERS M where (M.VALID=1)
;




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE ACTIVITIES ADD CONSTRAINT PK_ACTIVITIES PRIMARY KEY (ID);
ALTER TABLE DISTRICTS ADD CONSTRAINT PK_DISTRICTS PRIMARY KEY (ID);
ALTER TABLE JOBS ADD CONSTRAINT PK_JOBS PRIMARY KEY (ID);
ALTER TABLE MANAGERS ADD CONSTRAINT PK_MANAGERS PRIMARY KEY (ID);
ALTER TABLE QUESTIONNAIRES ADD CONSTRAINT PK_QUESTIONNAIRES PRIMARY KEY (ID);
ALTER TABLE SUMMARIES ADD CONSTRAINT PK_SUMMARIES PRIMARY KEY (ID);
ALTER TABLE SUMMARY_ADDITIONAL_EDUCATIONS ADD CONSTRAINT PK_SUMMARY_ADDITIONAL_EDUCA PRIMARY KEY (ID);
ALTER TABLE SUMMARY_EDUCATIONS ADD CONSTRAINT PK_SUMMARY_EDUCATIONS PRIMARY KEY (ID);
ALTER TABLE SUMMARY_RECOMENDATIONS ADD CONSTRAINT PK_SUMMARY_RECOMENDATIONS PRIMARY KEY (ID);
ALTER TABLE SUMMARY_WORK_ACTIVITIES ADD CONSTRAINT PK_SUMMARY_WORK_ACTIVITIES PRIMARY KEY (ID);
ALTER TABLE USERS_TUNINGS ADD CONSTRAINT PK_USERS_TUNINGS PRIMARY KEY (USER_NAME, ITEM_NAME);
ALTER TABLE VACANSIES ADD CONSTRAINT PK_VACANSIES PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE QUESTIONNAIRES ADD CONSTRAINT FK_QUESTIONNAIRES01 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS (ID) ON UPDATE CASCADE
  USING INDEX FK_QUESTIONNAIRES;
ALTER TABLE SUMMARIES ADD CONSTRAINT FK_SUMMARIES01 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS (ID) ON UPDATE CASCADE
  USING INDEX FK_SUMMARIES;
ALTER TABLE SUMMARIES ADD CONSTRAINT FK_SUMMARIES02 FOREIGN KEY (RESIDING_DISTRICT_ID) REFERENCES DISTRICTS (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARIES ADD CONSTRAINT FK_SUMMARIES03 FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARIES ADD CONSTRAINT FK_SUMMARIES04 FOREIGN KEY (JOB_ID) REFERENCES JOBS (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARY_ADDITIONAL_EDUCATIONS ADD CONSTRAINT FK_SUMMARY_ADDITIONAL_EDUCA FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARIES (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARY_EDUCATIONS ADD CONSTRAINT FK_SUMMARY_EDUCATIONS FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARIES (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARY_RECOMENDATIONS ADD CONSTRAINT FK_SUMMARY_RECOMENDATIONS01 FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARIES (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARY_WORK_ACTIVITIES ADD CONSTRAINT FK_SMR_WORK_ACTIVITIES01 FOREIGN KEY (SUMMARY_ID) REFERENCES SUMMARIES (ID) ON UPDATE CASCADE;
ALTER TABLE SUMMARY_WORK_ACTIVITIES ADD CONSTRAINT FK_SMR_WORK_ACTIVITIES02 FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES (ID) ON UPDATE CASCADE;
ALTER TABLE VACANSIES ADD CONSTRAINT FK_VACANSIES01 FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS (ID) ON UPDATE CASCADE;
ALTER TABLE VACANSIES ADD CONSTRAINT FK_VACANSIES02 FOREIGN KEY (ACTIVITY_ID) REFERENCES ACTIVITIES (ID) ON UPDATE CASCADE;
ALTER TABLE VACANSIES ADD CONSTRAINT FK_VACANSIES03 FOREIGN KEY (JOB_ID) REFERENCES JOBS (ID) ON UPDATE CASCADE;
ALTER TABLE VACANSIES ADD CONSTRAINT FK_VACANSIES04 FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS (ID) ON UPDATE CASCADE;


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE INDEX ACTIVITIES_IDX1 ON ACTIVITIES (NAME);
CREATE INDEX DISTRICTS_IDX1 ON DISTRICTS (NAME);
CREATE INDEX JOBS_IDX1 ON JOBS (NAME);
CREATE INDEX MANAGERS_IDX1 ON MANAGERS (NAME);
CREATE INDEX QUESTIONNAIRES_IDX1 ON QUESTIONNAIRES (ACQUAINTANCE_AIM);
CREATE INDEX QUESTIONNAIRES_IDX10 ON QUESTIONNAIRES (OPPONENT_EDUCATION_LEVEL);
CREATE INDEX QUESTIONNAIRES_IDX2 ON QUESTIONNAIRES (YOUR_SEX, ID);
CREATE INDEX QUESTIONNAIRES_IDX3 ON QUESTIONNAIRES (OPPONENT_SEX, ID);
CREATE INDEX QUESTIONNAIRES_IDX4 ON QUESTIONNAIRES (OPPONENT_START_AGE);
CREATE INDEX QUESTIONNAIRES_IDX5 ON QUESTIONNAIRES (OPPONENT_STOP_AGE);
CREATE INDEX QUESTIONNAIRES_IDX6 ON QUESTIONNAIRES (OPPONENT_START_HEIGH);
CREATE INDEX QUESTIONNAIRES_IDX7 ON QUESTIONNAIRES (OPPONENT_STOP_HEIGH);
CREATE INDEX QUESTIONNAIRES_IDX8 ON QUESTIONNAIRES (OPPONENT_START_WEIGHT);
CREATE INDEX QUESTIONNAIRES_IDX9 ON QUESTIONNAIRES (OPPONENT_STOP_WEIGHT);
CREATE INDEX SUMMARIES_IDX1 ON SUMMARIES (BIRTHDAY);
CREATE INDEX SUMMARIES_IDX2 ON SUMMARIES (SEX, ID);
CREATE INDEX SUMMARIES_IDX3 ON SUMMARIES (WORK_SCHEDULE, ID);
CREATE INDEX SUMMARIES_IDX4 ON SUMMARIES (EDUCATION_LEVEL, ID);
CREATE INDEX SUMMARIES_IDX5 ON SUMMARIES (WORK_EXPERIENCE, ID);
CREATE INDEX SUMMARIES_IDX6 ON SUMMARIES (STATUS_DOC, ID);
CREATE INDEX SUMMARIES_IDX7 ON SUMMARIES (NUMBER_DOC);
CREATE INDEX SUMMARIES_IDX8 ON SUMMARIES (LAST_CHANGE_STATUS_DATE);
CREATE DESCENDING INDEX VACANSIES_IDX1 ON VACANSIES (MIN_AGE);
CREATE INDEX VACANSIES_IDX2 ON VACANSIES (MAX_AGE);
CREATE INDEX VACANSIES_IDX3 ON VACANSIES (WORK_SCHEDULE, ID);
CREATE INDEX VACANSIES_IDX4 ON VACANSIES (SEX, ID);
CREATE INDEX VACANSIES_IDX5 ON VACANSIES (EDUCATION_LEVEL);
CREATE INDEX VACANSIES_IDX6 ON VACANSIES (PAYMENT);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: ACTIVITIES_BI */
CREATE TRIGGER ACTIVITIES_BI FOR ACTIVITIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ACTIVITIES_ID,1);
END
^

/* Trigger: ACTIVITIES_BU0 */
CREATE TRIGGER ACTIVITIES_BU0 FOR ACTIVITIES
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: DISTRICTS_BI */
CREATE TRIGGER DISTRICTS_BI FOR DISTRICTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_DISTRICTS_ID,1);
END
^

/* Trigger: DISTRICTS_BU0 */
CREATE TRIGGER DISTRICTS_BU0 FOR DISTRICTS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: JOBS_BI */
CREATE TRIGGER JOBS_BI FOR JOBS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_JOBS_ID,1);
END
^

/* Trigger: JOBS_BU0 */
CREATE TRIGGER JOBS_BU0 FOR JOBS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: MANAGERS_BI */
CREATE TRIGGER MANAGERS_BI FOR MANAGERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MANAGERS_ID,1);
END
^

/* Trigger: MANAGERS_BU0 */
CREATE TRIGGER MANAGERS_BU0 FOR MANAGERS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: QUESTIONNAIRES_BI */
CREATE TRIGGER QUESTIONNAIRES_BI FOR QUESTIONNAIRES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_QUESTIONNAIRES_ID,1);
END
^

/* Trigger: QUESTIONNAIRES_BU0 */
CREATE TRIGGER QUESTIONNAIRES_BU0 FOR QUESTIONNAIRES
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
 NEW.LAST_CHANGE_STATUS_DATE = CURRENT_DATE;
end
^

/* Trigger: SMR_ADD_ED_BI */
CREATE TRIGGER SMR_ADD_ED_BI FOR SUMMARY_ADDITIONAL_EDUCATIONS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SMR_ADD_EDUCATIONS_ID,1);
END
^

/* Trigger: SMR_ADD_ED_BU0 */
CREATE TRIGGER SMR_ADD_ED_BU0 FOR SUMMARY_ADDITIONAL_EDUCATIONS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: SUMMARIES_BI */
CREATE TRIGGER SUMMARIES_BI FOR SUMMARIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SUMMARIES_ID,1);
  if ((NEW.DONT_PUBLISH=1) and (NEW.STATUS_DOC=1)) then
   NEW.STATUS_DOC = 0;
END
^

/* Trigger: SUMMARIES_BU0 */
CREATE TRIGGER SUMMARIES_BU0 FOR SUMMARIES
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
 NEW.LAST_CHANGE_STATUS_DATE = CURRENT_DATE;
 if ((NEW.DONT_PUBLISH=1) and (NEW.STATUS_DOC=1)) then
  NEW.STATUS_DOC = 0;
end
^

/* Trigger: SUMMARY_EDUCATIONS_BI */
CREATE TRIGGER SUMMARY_EDUCATIONS_BI FOR SUMMARY_EDUCATIONS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SUMMARY_EDUCATIONS_ID,1);
END
^

/* Trigger: SUMMARY_EDUCATIONS_BU0 */
CREATE TRIGGER SUMMARY_EDUCATIONS_BU0 FOR SUMMARY_EDUCATIONS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: SUMMARY_RECOMENDATIONS_BI */
CREATE TRIGGER SUMMARY_RECOMENDATIONS_BI FOR SUMMARY_RECOMENDATIONS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SUMMARY_RECOMENDATIONS_ID,1);
END
^

/* Trigger: SUMMARY_RECOMENDATIONS_BU0 */
CREATE TRIGGER SUMMARY_RECOMENDATIONS_BU0 FOR SUMMARY_RECOMENDATIONS
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: SUMMARY_WORK_ACTIVITIES_BI */
CREATE TRIGGER SUMMARY_WORK_ACTIVITIES_BI FOR SUMMARY_WORK_ACTIVITIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SUMMARY_WORK_ACTIVITIES_ID,1);
END
^

/* Trigger: SUMMARY_WORK_ACTIVITIES_BU0 */
CREATE TRIGGER SUMMARY_WORK_ACTIVITIES_BU0 FOR SUMMARY_WORK_ACTIVITIES
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
end
^

/* Trigger: VACANSIES_BI */
CREATE TRIGGER VACANSIES_BI FOR VACANSIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_VACANSIES_ID,1);
END
^

/* Trigger: VACANSIES_BU0 */
CREATE TRIGGER VACANSIES_BU0 FOR VACANSIES
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
 NEW.CHANGER = CURRENT_USER;
 NEW.CHANGE_DATE = CURRENT_TIMESTAMP;
 NEW.LAST_CHANGE_STATUS_DATE = CURRENT_DATE;
end
^

SET TERM ; ^



/******************************************************************************/
/****                          Stored Procedures                           ****/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE SET_USER_TUNING (
    ITEM_NAME VARCHAR(100),
    TUNING BLOB SUB_TYPE 0 SEGMENT SIZE 80)
AS
DECLARE VARIABLE USER_NAME VARCHAR(31);
begin
 for select UT.USER_NAME
       from USERS_TUNINGS UT
      where (UT.USER_NAME = current_user) and  (UT.ITEM_NAME = :ITEM_NAME)
       into :USER_NAME
  as cursor UT_CURSOR
 do
  update USERS_TUNINGS UT
     set UT.TUNING = :TUNING
   where current of UT_CURSOR;
 if (USER_NAME is NULL) then
  insert into USERS_TUNINGS (ITEM_NAME,TUNING) values (:ITEM_NAME,:TUNING);
end
^


SET TERM ; ^


/******************************************************************************/
/****                                Roles                                 ****/
/******************************************************************************/

CREATE ROLE SYSDBA;
CREATE ROLE USRS;


/******************************************************************************/
/****                             Descriptions                             ****/
/******************************************************************************/

DESCRIBE TABLE ACTIVITIES
'Справочник областей деятельности';

DESCRIBE TABLE DISTRICTS
'Справочник районов';

DESCRIBE TABLE JOBS
'Справочник должностей';

DESCRIBE TABLE MANAGERS
'Справочник менеджеров';

DESCRIBE TABLE QUESTIONNAIRES
'Список анкет';

DESCRIBE TABLE SUMMARIES
'Список резюме';

DESCRIBE TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Сведения о дополнительном образовании к резюме';

DESCRIBE TABLE SUMMARY_EDUCATIONS
'Сведения об образовании к резюме';

DESCRIBE TABLE SUMMARY_RECOMENDATIONS
'Рекомендации к резюме';

DESCRIBE TABLE SUMMARY_WORK_ACTIVITIES
'Сведения о трудовой деятельности к резюме';

DESCRIBE TABLE USERS_TUNINGS
'Настройки пользователей';

DESCRIBE TABLE VACANSIES
'Список вакансий';



/* Fields descriptions */

DESCRIBE FIELD CHANGER TABLE ACTIVITIES
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE ACTIVITIES
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE ACTIVITIES
'Дата создания';

DESCRIBE FIELD CREATOR TABLE ACTIVITIES
'Пользователь создавший запись';

DESCRIBE FIELD ID TABLE ACTIVITIES
'Идентификатор';

DESCRIBE FIELD NAME TABLE ACTIVITIES
'Наименование';

DESCRIBE FIELD CHANGER TABLE DISTRICTS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE DISTRICTS
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE DISTRICTS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE DISTRICTS
'Пользователь создавший запись';

DESCRIBE FIELD ID TABLE DISTRICTS
'Идентификатор';

DESCRIBE FIELD NAME TABLE DISTRICTS
'Наименование';

DESCRIBE FIELD ACTIVITY_ID TABLE JOBS
'Идентификатор области деятельности';

DESCRIBE FIELD CHANGER TABLE JOBS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE JOBS
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE JOBS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE JOBS
'Пользователь создавший запись';

DESCRIBE FIELD ID TABLE JOBS
'Идентификатор';

DESCRIBE FIELD NAME TABLE JOBS
'Наименование';

DESCRIBE FIELD CHANGER TABLE MANAGERS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE MANAGERS
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE MANAGERS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE MANAGERS
'Пользователь создавший запись';

DESCRIBE FIELD ID TABLE MANAGERS
'Идентификатор';

DESCRIBE FIELD NAME TABLE MANAGERS
'Имя менеджера';

DESCRIBE FIELD PSWD TABLE MANAGERS
'Пароль';

DESCRIBE FIELD VALID TABLE MANAGERS
'Признак действительности';

DESCRIBE FIELD ACQUAINTANCE_AIM TABLE QUESTIONNAIRES
'Цель знакомства
0 - Брак
1 - Гражданский брак
2 - Отдых
3 - Спонсор
4 - Нетрадиционный вариант';

DESCRIBE FIELD ADDRESS TABLE QUESTIONNAIRES
'Адрес';

DESCRIBE FIELD CHANGER TABLE QUESTIONNAIRES
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE QUESTIONNAIRES
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE QUESTIONNAIRES
'Дата создания';

DESCRIBE FIELD CREATOR TABLE QUESTIONNAIRES
'Пользователь создавший запись';

DESCRIBE FIELD E_MAIL TABLE QUESTIONNAIRES
'E-mail';

DESCRIBE FIELD FIO TABLE QUESTIONNAIRES
'Ф.И.О.';

DESCRIBE FIELD ID TABLE QUESTIONNAIRES
'Идентификатор';

DESCRIBE FIELD LAST_CHANGE_STATUS_DATE TABLE QUESTIONNAIRES
'Дата последнего изменения статуса';

DESCRIBE FIELD MAIN_IN_HOMELIFE TABLE QUESTIONNAIRES
'Главное в семейной жизни';

DESCRIBE FIELD MANAGER_ID TABLE QUESTIONNAIRES
'Идентификатор менеджера';

DESCRIBE FIELD NEGATIVE_TRAIT TABLE QUESTIONNAIRES
'Отрицательные черты анкетируемого';

DESCRIBE FIELD NUMBER_DOC TABLE QUESTIONNAIRES
'Номер анкеты';

DESCRIBE FIELD OPPONENT_ACTIVITY TABLE QUESTIONNAIRES
'Область деятельности желаемой стороны';

DESCRIBE FIELD OPPONENT_ADDITIONAL_INFORMATION TABLE QUESTIONNAIRES
'Дополнительные сведения о желаемой стороне';

DESCRIBE FIELD OPPONENT_ALCOHOL_ATTITUDE TABLE QUESTIONNAIRES
'Отношение желаемой стороны к алкоголю';

DESCRIBE FIELD OPPONENT_CHILDREN_INFORMATION TABLE QUESTIONNAIRES
'Наличие детей, их возраст у желаемой стороны';

DESCRIBE FIELD OPPONENT_EDUCATION_LEVEL TABLE QUESTIONNAIRES
'Уровень образования желаемой стороны
0 - Не имеет значения
1 - Среднее
2 - Среднее специальное
3 - Незаконченное высшее
4 - Высшее
5 - Несколько высших
6 - Кандидат наук
7 - Доктор наук';

DESCRIBE FIELD OPPONENT_EYES_COLOR TABLE QUESTIONNAIRES
'Цвет глаз желаемой стороны';

DESCRIBE FIELD OPPONENT_HAIR_COLOR TABLE QUESTIONNAIRES
'Цвет волос желаемой стороны';

DESCRIBE FIELD OPPONENT_HOBBY TABLE QUESTIONNAIRES
'Любимое занятие желаемой стороны в свободное время';

DESCRIBE FIELD OPPONENT_LIVING_SPACE_CONDITION TABLE QUESTIONNAIRES
'Жилищные условия желаемой стороны';

DESCRIBE FIELD OPPONENT_MARRIAGE_STATUS TABLE QUESTIONNAIRES
'Брачное состояние желаемой стороны';

DESCRIBE FIELD OPPONENT_NATIONALITY TABLE QUESTIONNAIRES
'Национальность желаемой стороны';

DESCRIBE FIELD OPPONENT_OVER_PRIVACY TABLE QUESTIONNAIRES
'Другая собственность желаемой стороны';

DESCRIBE FIELD OPPONENT_SEX TABLE QUESTIONNAIRES
'Пол желаемой стороны
0 - женский
1 - мужской';

DESCRIBE FIELD OPPONENT_SMOKING_ATTITUDE TABLE QUESTIONNAIRES
'Отношение желаемой стороны к курению';

DESCRIBE FIELD OPPONENT_START_AGE TABLE QUESTIONNAIRES
'Минимальный возраст желаемой стороны';

DESCRIBE FIELD OPPONENT_START_HEIGH TABLE QUESTIONNAIRES
'Минимальный рост желаемой стороны';

DESCRIBE FIELD OPPONENT_START_WEIGHT TABLE QUESTIONNAIRES
'Минимальный вес желаемой стороны';

DESCRIBE FIELD OPPONENT_STOP_AGE TABLE QUESTIONNAIRES
'Максимальный возраст желаемой стороны';

DESCRIBE FIELD OPPONENT_STOP_HEIGH TABLE QUESTIONNAIRES
'Максимальный рост желаемой стороны';

DESCRIBE FIELD OPPONENT_STOP_WEIGHT TABLE QUESTIONNAIRES
'Максимальный вес желаемой стороны';

DESCRIBE FIELD OPPONENT_WISH_BABY_BIRTH TABLE QUESTIONNAIRES
'Желание иметь детей желаемой стороны
0 - Нет
1 - Да
2 - Возможно';

DESCRIBE FIELD OPPOSITE_PRIZE TABLE QUESTIONNAIRES
'Что анкетируемый ценит в мужчинах (женщинах)';

DESCRIBE FIELD PHONE TABLE QUESTIONNAIRES
'Телефон';

DESCRIBE FIELD POSITIVE_TRAIT TABLE QUESTIONNAIRES
'Положительные черты анкетируемого';

DESCRIBE FIELD STATUS_DOC TABLE QUESTIONNAIRES
'Статус анкеты
0 - не публиковать на сайте
1 - публиковать на сайте
2 - закрыта';

DESCRIBE FIELD YOUR_ACTIVITY TABLE QUESTIONNAIRES
'Область деятельности анкетируемого';

DESCRIBE FIELD YOUR_ADDITIONAL_INFORMATION TABLE QUESTIONNAIRES
'Дополнительные сведения об анкетируемом';

DESCRIBE FIELD YOUR_ALCOHOL_ATTITUDE TABLE QUESTIONNAIRES
'Отношение анкетируемого к алкоголю';

DESCRIBE FIELD YOUR_BIRTHDAY TABLE QUESTIONNAIRES
'День рождения анкетируемого';

DESCRIBE FIELD YOUR_CHILDREN_INFORMATION TABLE QUESTIONNAIRES
'Наличие детей, их возраст у анкетируемого';

DESCRIBE FIELD YOUR_EDUCATION_LEVEL TABLE QUESTIONNAIRES
'Уровень образования анкетируемого
0 - Не имеет значения
1 - Среднее
2 - Среднее специальное
3 - Незаконченное высшее
4 - Высшее
5 - Несколько высших
6 - Кандидат наук
7 - Доктор наук';

DESCRIBE FIELD YOUR_EYES_COLOR TABLE QUESTIONNAIRES
'Цвет глаз анкетируемого';

DESCRIBE FIELD YOUR_HAIR_COLOR TABLE QUESTIONNAIRES
'Цвет волос анкетируемого';

DESCRIBE FIELD YOUR_HEIGH TABLE QUESTIONNAIRES
'Рост анкетируемого';

DESCRIBE FIELD YOUR_HOBBY TABLE QUESTIONNAIRES
'Любимое занятие анкетируемого в свободное время';

DESCRIBE FIELD YOUR_LIVING_SPACE_CONDITION TABLE QUESTIONNAIRES
'Жилищные условия анкетируемого';

DESCRIBE FIELD YOUR_MARRIAGE_STATUS TABLE QUESTIONNAIRES
'Брачное состояние анкетируемого';

DESCRIBE FIELD YOUR_NATIONALITY TABLE QUESTIONNAIRES
'Национальность анкетируемого';

DESCRIBE FIELD YOUR_OVER_PRIVACY TABLE QUESTIONNAIRES
'Другая собственность анкетируемого';

DESCRIBE FIELD YOUR_SEX TABLE QUESTIONNAIRES
'Пол анкетируемого
0 - женский
1 - мужской';

DESCRIBE FIELD YOUR_SMOKING_ATTITUDE TABLE QUESTIONNAIRES
'Отношение анкетируемого к курению';

DESCRIBE FIELD YOUR_WEIGHT TABLE QUESTIONNAIRES
'Вес анкетируемого';

DESCRIBE FIELD YOUR_WISH_BABY_BIRTH TABLE QUESTIONNAIRES
'Желание анкетируемого иметь детей
0 - Нет
1 - Да
2 - Возможно';

DESCRIBE FIELD ACTIVITY_ID TABLE SUMMARIES
'Идентификатор области деятельности';

DESCRIBE FIELD BIRTHDAY TABLE SUMMARIES
'Дата рождения';

DESCRIBE FIELD CHANGER TABLE SUMMARIES
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE SUMMARIES
'Дата последнего изменения';

DESCRIBE FIELD COMPUTER_EXPERIENCE TABLE SUMMARIES
'Навыки работы с компьютером, оргтехникой, программным обеспечением';

DESCRIBE FIELD CONTACT_PHONE TABLE SUMMARIES
'Контактный телефон';

DESCRIBE FIELD CREATE_DATE TABLE SUMMARIES
'Дата создания';

DESCRIBE FIELD CREATOR TABLE SUMMARIES
'Пользователь создавший запись';

DESCRIBE FIELD DONT_PUBLISH TABLE SUMMARIES
'Не публиковать мои данные на сайте';

DESCRIBE FIELD EDUCATION_LEVEL TABLE SUMMARIES
'Уровень образования
0 - Не имеет значения
1 - Среднее
2 - Среднее специальное
3 - Незаконченное высшее
4 - Высшее
5 - Несколько высших
6 - Кандидат наук
7 - Доктор наук';

DESCRIBE FIELD E_MAIL TABLE SUMMARIES
'E-mail';

DESCRIBE FIELD FAMILY_STATUS TABLE SUMMARIES
'Семейное положение,сведения о детях';

DESCRIBE FIELD FIO TABLE SUMMARIES
'Ф.И.О.';

DESCRIBE FIELD FOREIGN_LANGUAGE TABLE SUMMARIES
'Владение иностранными языками';

DESCRIBE FIELD FOTO TABLE SUMMARIES
'Фотография';

DESCRIBE FIELD HAVE_CAR TABLE SUMMARIES
'Наличие личного автомобиля
0 - Нет
1 - Есть';

DESCRIBE FIELD HAVE_DRIVING_LICENCE TABLE SUMMARIES
'Водительские права
0 - Нет
1 - Есть';

DESCRIBE FIELD HOBBIES TABLE SUMMARIES
'Увлечения, хобби';

DESCRIBE FIELD ID TABLE SUMMARIES
'Идентификатор';

DESCRIBE FIELD JOB_ID TABLE SUMMARIES
'Идентификатор предполагаемой должности';

DESCRIBE FIELD LAST_CHANGE_STATUS_DATE TABLE SUMMARIES
'Дата последнего изменения статуса';

DESCRIBE FIELD MANAGER_ID TABLE SUMMARIES
'Идентификатор менеджера';

DESCRIBE FIELD MANAGER_NOTES TABLE SUMMARIES
'Заметки менеджера';

DESCRIBE FIELD MINIMAL_SUPPOSED_INCOME TABLE SUMMARIES
'Минимальный предполагаемый доход';

DESCRIBE FIELD MOBILE_PHONE TABLE SUMMARIES
'Мобильный телефон';

DESCRIBE FIELD NUMBER_DOC TABLE SUMMARIES
'Номер резюме';

DESCRIBE FIELD OTHER_INFORMATION TABLE SUMMARIES
'Дополнительные сведения';

DESCRIBE FIELD OTHER_POSSIBLE_JOBS TABLE SUMMARIES
'Другие возможные должности';

DESCRIBE FIELD PASSPORT_DATA TABLE SUMMARIES
'Паспортные данные';

DESCRIBE FIELD PERSONAL_QUALITIES TABLE SUMMARIES
'Личные качества';

DESCRIBE FIELD PROFESSIONAL_ACHIEVEMENTS TABLE SUMMARIES
'Пример профессиональных достижений';

DESCRIBE FIELD PROFESSIONAL_SKILL TABLE SUMMARIES
'Профессиональные навыки, знания';

DESCRIBE FIELD PUBLISH_IN_LIST TABLE SUMMARIES
'Публиковать мое резюме в списке';

DESCRIBE FIELD REGISTRATION_ADDRESS TABLE SUMMARIES
'Адрес регистрации';

DESCRIBE FIELD RESIDING_ADDRESS TABLE SUMMARIES
'Адрес проживания';

DESCRIBE FIELD RESIDING_DISTRICT_ID TABLE SUMMARIES
'Идентификатор района проживания';

DESCRIBE FIELD SERVICE_PHONE TABLE SUMMARIES
'Служебный телефон';

DESCRIBE FIELD SEX TABLE SUMMARIES
'Пол
0 - женский
1 - мужской';

DESCRIBE FIELD STATUS_DOC TABLE SUMMARIES
'Статус резюме
0 - не публиковать на сайте
1 - публиковать на сайте
2 - закрыто';

DESCRIBE FIELD WORK_EXPERIENCE TABLE SUMMARIES
'Опыт работы
0 - Не имеет значения
1 - Без опыта
2 - Менее 1 года
3 - Более 1 года
4 - Более 3 лет
5 - Более 5 лет';

DESCRIBE FIELD WORK_SCHEDULE TABLE SUMMARIES
'График работы
0 - Не имеет значения
1 - Полная занятость
2 - По совместительству
3 - Временная, проектная работа
4 - Удаленная работа';

DESCRIBE FIELD CHANGER TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Дата последнего изменения';

DESCRIBE FIELD COURSE_NAME TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Наименование курса';

DESCRIBE FIELD CREATE_DATE TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Пользователь создавший запись';

DESCRIBE FIELD EDUCATIONAL_INSTITUTION_NAME TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Наименование учебного заведения';

DESCRIBE FIELD GRADUATION_YEAR TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Год окончания';

DESCRIBE FIELD ID TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Идентификатор';

DESCRIBE FIELD SUMMARY_ID TABLE SUMMARY_ADDITIONAL_EDUCATIONS
'Идентификатор резюме';

DESCRIBE FIELD CHANGER TABLE SUMMARY_EDUCATIONS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE SUMMARY_EDUCATIONS
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE SUMMARY_EDUCATIONS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE SUMMARY_EDUCATIONS
'Пользователь создавший запись';

DESCRIBE FIELD EDUCATIONAL_INSTITUTION_NAME TABLE SUMMARY_EDUCATIONS
'Наименование учебного заведения';

DESCRIBE FIELD ENTRANCE_YEAR TABLE SUMMARY_EDUCATIONS
'Год поступления';

DESCRIBE FIELD FACULTY_NAME TABLE SUMMARY_EDUCATIONS
'Факультет';

DESCRIBE FIELD GRADUATION_YEAR TABLE SUMMARY_EDUCATIONS
'Год окончания';

DESCRIBE FIELD ID TABLE SUMMARY_EDUCATIONS
'Идентификатор';

DESCRIBE FIELD QUALIFICATION TABLE SUMMARY_EDUCATIONS
'Квалификация';

DESCRIBE FIELD SUMMARY_ID TABLE SUMMARY_EDUCATIONS
'Идентификатор резюме';

DESCRIBE FIELD CHANGER TABLE SUMMARY_RECOMENDATIONS
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE SUMMARY_RECOMENDATIONS
'Дата последнего изменения';

DESCRIBE FIELD CONTACT_PHONE TABLE SUMMARY_RECOMENDATIONS
'Контактный телефон';

DESCRIBE FIELD CREATE_DATE TABLE SUMMARY_RECOMENDATIONS
'Дата создания';

DESCRIBE FIELD CREATOR TABLE SUMMARY_RECOMENDATIONS
'Пользователь создавший запись';

DESCRIBE FIELD FIO TABLE SUMMARY_RECOMENDATIONS
'ФИО рекомендателя';

DESCRIBE FIELD ID TABLE SUMMARY_RECOMENDATIONS
'Идентификатор';

DESCRIBE FIELD JOB TABLE SUMMARY_RECOMENDATIONS
'Должность';

DESCRIBE FIELD ORGANIZATION_NAME TABLE SUMMARY_RECOMENDATIONS
'Место работы';

DESCRIBE FIELD SUMMARY_ID TABLE SUMMARY_RECOMENDATIONS
'Идентификатор резюме';

DESCRIBE FIELD ACTIVITY_ID TABLE SUMMARY_WORK_ACTIVITIES
'Идентификатор области деятельности';

DESCRIBE FIELD CHANGER TABLE SUMMARY_WORK_ACTIVITIES
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE SUMMARY_WORK_ACTIVITIES
'Дата последнего изменения';

DESCRIBE FIELD CREATE_DATE TABLE SUMMARY_WORK_ACTIVITIES
'Дата создания';

DESCRIBE FIELD CREATOR TABLE SUMMARY_WORK_ACTIVITIES
'Пользователь создавший запись';

DESCRIBE FIELD ENTRANCE_DATE TABLE SUMMARY_WORK_ACTIVITIES
'Дата поступления на работу';

DESCRIBE FIELD FUNCTIONAL_DUTIES TABLE SUMMARY_WORK_ACTIVITIES
'Функциональные обязанности';

DESCRIBE FIELD ID TABLE SUMMARY_WORK_ACTIVITIES
'Идентификатор';

DESCRIBE FIELD JOB TABLE SUMMARY_WORK_ACTIVITIES
'Должность';

DESCRIBE FIELD ORGANIZATION_NAME TABLE SUMMARY_WORK_ACTIVITIES
'Наименование организации';

DESCRIBE FIELD RETIRING_DATE TABLE SUMMARY_WORK_ACTIVITIES
'Дата увольнения с работы';

DESCRIBE FIELD SUMMARY_ID TABLE SUMMARY_WORK_ACTIVITIES
'Идентификатор резюме';

DESCRIBE FIELD ITEM_NAME TABLE USERS_TUNINGS
'Имя объекта';

DESCRIBE FIELD TUNING TABLE USERS_TUNINGS
'Настройки';

DESCRIBE FIELD USER_NAME TABLE USERS_TUNINGS
'Имя пользователя';

DESCRIBE FIELD ACTIVITY_ID TABLE VACANSIES
'Идентификатор области деятельности';

DESCRIBE FIELD ADDITIONAL_INFORMATION TABLE VACANSIES
'Дополнительные сведения';

DESCRIBE FIELD APPEARANCE TABLE VACANSIES
'Внешность';

DESCRIBE FIELD ARMY_DUTY TABLE VACANSIES
'Служба в ВС';

DESCRIBE FIELD BOSS TABLE VACANSIES
'Руководитель';

DESCRIBE FIELD CHANGER TABLE VACANSIES
'Пользователь сделавший последнее изменение';

DESCRIBE FIELD CHANGE_DATE TABLE VACANSIES
'Дата последнего изменения';

DESCRIBE FIELD CHILDREN_INFORMATION TABLE VACANSIES
'Cведения о детях';

DESCRIBE FIELD COMPUTER_EXPERIENCE TABLE VACANSIES
'Навыки в сфере компьютерных технологий';

DESCRIBE FIELD CPHONE TABLE VACANSIES
'Телефон';

DESCRIBE FIELD CREATE_DATE TABLE VACANSIES
'Дата создания';

DESCRIBE FIELD CREATOR TABLE VACANSIES
'Пользователь создавший запись';

DESCRIBE FIELD DISTRICT_ID TABLE VACANSIES
'Идентификатор района проживания';

DESCRIBE FIELD EDUCATION TABLE VACANSIES
'Образование (подробнее)';

DESCRIBE FIELD EDUCATION_LEVEL TABLE VACANSIES
'Уровень образования
0 - Не имеет значения
1 - Среднее
2 - Среднее специальное
3 - Незаконченное высшее
4 - Высшее
5 - Несколько высших
6 - Кандидат наук
7 - Доктор наук';

DESCRIBE FIELD EMPLOYEE_STUDIES TABLE VACANSIES
'Обучение сотрудников';

DESCRIBE FIELD E_MAIL TABLE VACANSIES
'E-mail';

DESCRIBE FIELD FAMILY_STATUS TABLE VACANSIES
'Семейное положение,сведения о детях';

DESCRIBE FIELD FOREIGN_LANGUAGE TABLE VACANSIES
'Владение иностранными языками';

DESCRIBE FIELD FOR_INET_ONLY TABLE VACANSIES
'Только для публикации на сайте';

DESCRIBE FIELD HAVE_CAR TABLE VACANSIES
'Наличие личного автомобиля
0 - Нет
1 - Есть
2 - Не имеет значения';

DESCRIBE FIELD HAVE_DRIVING_LICENCE TABLE VACANSIES
'Водительские права
0 - Нет
1 - Есть
2 - Не имеет значения';

DESCRIBE FIELD HAVE_HOME_PHONE TABLE VACANSIES
'Наличие домашнего телефона
0 - Нет
1 - Есть
2 - Не имеет значения';

DESCRIBE FIELD ID TABLE VACANSIES
'Идентификатор';

DESCRIBE FIELD IMMEDIATE_BOSS TABLE VACANSIES
'Кому подчиняется';

DESCRIBE FIELD JOB_DUTIES TABLE VACANSIES
'Должностные обязанности';

DESCRIBE FIELD JOB_ID TABLE VACANSIES
'Идентификатор должности';

DESCRIBE FIELD LAST_CHANGE_STATUS_DATE TABLE VACANSIES
'Дата последнего изменения статуса';

DESCRIBE FIELD MANAGER_ID TABLE VACANSIES
'Идентификатор менеджера';

DESCRIBE FIELD MANAGER_NOTES TABLE VACANSIES
'Заметки менеджера';

DESCRIBE FIELD MARRIAGE_STATUS TABLE VACANSIES
'Семейное положение 
0 - в браке не состою
1 - зарегистрированный брак
2 - гражданский брак
3 - в разводе
4 - вдовец/вдова';

DESCRIBE FIELD MAX_AGE TABLE VACANSIES
'Максимальный возраст';

DESCRIBE FIELD MIN_AGE TABLE VACANSIES
'Минимальный возраст';

DESCRIBE FIELD NUMBER_DOC TABLE VACANSIES
'Номер вакансии';

DESCRIBE FIELD ORGANIZATION_NAME TABLE VACANSIES
'Наименование организации';

DESCRIBE FIELD OVERTIME_WORK_PAYED TABLE VACANSIES
'Компенсация за переработку';

DESCRIBE FIELD PAYMENT TABLE VACANSIES
'Оплата труда после испытательного срока, руб.';

DESCRIBE FIELD PERSONS_UNDER TABLE VACANSIES
'Количество человек в подчинении';

DESCRIBE FIELD PRIVILEGE TABLE VACANSIES
'Льготы';

DESCRIBE FIELD PROSPECT_PAYMENT TABLE VACANSIES
'Оплата труда в перспективе';

DESCRIBE FIELD REGISTRATION TABLE VACANSIES
'Прописка';

DESCRIBE FIELD RESPONSIBLE_PERSON TABLE VACANSIES
'Ответственное лицо';

DESCRIBE FIELD RISE_PROSPECT TABLE VACANSIES
'Перспективы роста';

DESCRIBE FIELD SALARY_PAYED TABLE VACANSIES
'Зарплата выплачивается';

DESCRIBE FIELD SELECTION_PERSON TABLE VACANSIES
'Кто будет проводить отбор';

DESCRIBE FIELD SEX TABLE VACANSIES
'Пол
0 - женский
1 - мужской
2 - не имеет значения';

DESCRIBE FIELD SPESIAL_SKILLS TABLE VACANSIES
'Специальные знания, навыки';

DESCRIBE FIELD STATUS_DOC TABLE VACANSIES
'Статус вакансии
0 - не публиковать на сайте
1 - публиковать на сайте
2 - закрыта';

DESCRIBE FIELD TRIAL_PAYMENT TABLE VACANSIES
'Оплата труда на испытательный срок, руб.';

DESCRIBE FIELD TRIAL_PERIOD TABLE VACANSIES
'Испытательный срок, месяцы';

DESCRIBE FIELD WORK_DAY TABLE VACANSIES
'Рабочий день, часы';

DESCRIBE FIELD WORK_EXPERIENCE TABLE VACANSIES
'Опыт работы
0 - Не имеет значения
1 - Без опыта
2 - Менее 1 года
3 - Более 1 года
4 - Более 3 лет
5 - Более 5 лет';

DESCRIBE FIELD WORK_SCHEDULE TABLE VACANSIES
'График работы
0 - Не имеет значения
1 - Полная занятость
2 - По совместительству
3 - Временная, проектная работа
4 - Удаленная работа';

DESCRIBE FIELD WORK_WEEK TABLE VACANSIES
'Рабочая неделя, дни';



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT SELECT, REFERENCES ON USER_LIST TO USERLIST;

/* Privileges of roles */
GRANT ALL ON ACTIVITIES TO USRS;
GRANT ALL ON DISTRICTS TO USRS;
GRANT ALL ON JOBS TO USRS;
GRANT SELECT, REFERENCES ON MANAGERS TO USRS;
GRANT ALL ON QUESTIONNAIRES TO USRS;
GRANT ALL ON SUMMARIES TO USRS;
GRANT ALL ON SUMMARY_ADDITIONAL_EDUCATIONS TO USRS;
GRANT ALL ON SUMMARY_EDUCATIONS TO USRS;
GRANT ALL ON SUMMARY_RECOMENDATIONS TO USRS;
GRANT ALL ON SUMMARY_WORK_ACTIVITIES TO USRS;
GRANT ALL ON USERS_TUNINGS TO USRS;
GRANT ALL ON VACANSIES TO USRS;
GRANT EXECUTE ON PROCEDURE SET_USER_TUNING TO USRS;

/* Privileges of triggers */
GRANT UPDATE, REFERENCES ON MANAGERS TO TRIGGER MANAGERS_BU0;
GRANT UPDATE, REFERENCES ON QUESTIONNAIRES TO TRIGGER QUESTIONNAIRES_BU0;
GRANT UPDATE, REFERENCES ON SUMMARY_ADDITIONAL_EDUCATIONS TO TRIGGER SMR_ADD_ED_BU0;
GRANT UPDATE, REFERENCES ON SUMMARIES TO TRIGGER SUMMARIES_BI;
GRANT UPDATE, REFERENCES ON SUMMARIES TO TRIGGER SUMMARIES_BU0;
GRANT UPDATE, REFERENCES ON SUMMARY_EDUCATIONS TO TRIGGER SUMMARY_EDUCATIONS_BU0;
GRANT UPDATE, REFERENCES ON SUMMARY_RECOMENDATIONS TO TRIGGER SUMMARY_RECOMENDATIONS_BU0;
GRANT UPDATE, REFERENCES ON SUMMARY_WORK_ACTIVITIES TO TRIGGER SUMMARY_WORK_ACTIVITIES_BU0;
GRANT UPDATE, REFERENCES ON VACANSIES TO TRIGGER VACANSIES_BU0;
